var sweety ="Sweety";
var cutie ="Cutie";
console.log("====Before Swap====");
console.log(sweety);
console.log(cutie);
var temp="Sweety";
sweety = cutie;
cutie=temp;
console.log("====After Swap====");
console.log(sweety);
console.log(cutie);

var num1 =100;
var num2 =200;
var num3 =300;
console.log("====Before Swap====");
console.log(num1);
console.log(num2);
console.log(num3);
var temp1 =100;
var temp2 =200;
num1=temp2;
num2=num3;
num3=temp1;
console.log("====After Swap====");
console.log(num1);
console.log(num2);
console.log(num3);